/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BannerManager: typeof import('./src/components/catalog/BannerManager.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    CardForm: typeof import('./src/components/CardForm.vue')['default']
    CardManager: typeof import('./src/components/catalog/CardManager.vue')['default']
    CardSelectorModal: typeof import('./src/components/deck/CardSelectorModal.vue')['default']
    ConditionEditor: typeof import('./src/components/deck/ConditionEditor.vue')['default']
    DeckEditor: typeof import('./src/components/deck/DeckEditor.vue')['default']
    DeckManager: typeof import('./src/components/catalog/DeckManager.vue')['default']
    EventGoupModal: typeof import('./src/components/deck/EventGoupModal.vue')['default']
    EventGroupModal: typeof import('./src/components/deck/EventGroupModal.vue')['default']
    LogicManager: typeof import('./src/components/catalog/LogicManager.vue')['default']
    TagSelector: typeof import('./src/components/common/TagSelector.vue')['default']
    WishResultOverlay: typeof import('./src/components/WishResultOverlay.vue')['default']
  }
}
