name: Release
on:
  push: 
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v7

      - name: Extract version from tag
        id: version
        run: |
          TAG_VERSION="${GITHUB_REF_NAME#v}"
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
      
      - name: Verify version consistency
        run: |
          if [[ "${{ github.ref_type }}" != "tag" ]]; then    # 分支测试时跳过版本检查
            echo "分支测试, 跳过版本一致性检查"
            exit 0
          fi
          TAG_VERSION="${{ steps.version.outputs.version }}"
          PACKAGE_VERSION=$(jq -r '.version' package.json)
          CARGO_VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' src-tauri/Cargo.toml | head -1)

          TAURI_RAW_VERSION=$(jq -r '.version' src-tauri/tauri.conf.json)
          if [[ "$TAURI_RAW_VERSION" == "../package.json" ]]; then
            TAURI_VERSION="$PACKAGE_VERSION"   # use package.json version
          else
            TAURI_VERSION="$TAURI_RAW_VERSION"
          fi

          echo "TAG version: $TAG_VERSION"
          echo "package.json: $PACKAGE_VERSION"
          echo "Cargo.toml: $CARGO_VERSION"
          echo "tauri.conf.json: $TAURI_VERSION"

          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ] || \
             [ "$TAG_VERSION" != "$CARGO_VERSION" ] || \
             [ "$TAG_VERSION" != "$TAURI_VERSION" ]; then
            echo "版本不一致，终止构建！"
            exit 1
          fi
          echo "版本一致"
  
  build-windows:
    needs: check-version
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      
      - name: Install frontend dependencies
        run: npm ci
      
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
          cache-on-failure: true
      
      - name: Build and upload Tauri app (Windows)
        uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Wishes · 众愿 v${{ needs.check-version.outputs.version }}"
          generateReleaseNotes: true
          releaseDraft: true
          prerelease: false
          releaseBody: ${{ join(github.event.commits.*.message, '\n') }}
          args: ""
